export const EDGE_ONLINE_VOICES = Object.freeze([
  {
    id: "en-US-AriaNeural",
    name: "Aria",
    language: "en",
    region: "US",
    gender: "female",
  },
  {
    id: "en-US-JennyNeural",
    name: "Jenny",
    language: "en",
    region: "US",
    gender: "female",
  },
  {
    id: "en-US-GuyNeural",
    name: "Guy",
    language: "en",
    region: "US",
    gender: "male",
  },
  {
    id: "en-US-ChristopherNeural",
    name: "Christopher",
    language: "en",
    region: "US",
    gender: "male",
  },
  {
    id: "en-GB-SoniaNeural",
    name: "Sonia",
    language: "en",
    region: "GB",
    gender: "female",
  },
  {
    id: "en-GB-LibbyNeural",
    name: "Libby",
    language: "en",
    region: "GB",
    gender: "female",
  },
  {
    id: "en-GB-RyanNeural",
    name: "Ryan",
    language: "en",
    region: "GB",
    gender: "male",
  },
  {
    id: "en-GB-ThomasNeural",
    name: "Thomas",
    language: "en",
    region: "GB",
    gender: "male",
  },
  {
    id: "es-ES-ElviraNeural",
    name: "Elvira",
    language: "es",
    region: "ES",
    gender: "female",
  },
  {
    id: "es-ES-XimenaNeural",
    name: "Ximena",
    language: "es",
    region: "ES",
    gender: "female",
  },
  {
    id: "es-ES-AlvaroNeural",
    name: "Álvaro",
    language: "es",
    region: "ES",
    gender: "male",
  },
]);
